### ISSUE TITLE
Update to latest FSharp.FOrmatting

### ISSUE THREAD

**Issue by dsyme** [fsprojects/fsharp-core-api-docs#6]
FSharp.Formatting v5.0.4 has been released.

This repo builds using v4.0 FSharp.Formatting.MetadataFormat.  This has been improved a little in v5.0, now called FSharp.Formatting.ApiDocs.  We should update and iterate on improved SIgnatures etc.

**Comment by baronfel** [comment]
Closing because @MecuSorin just fixed this.
